/*
Receipt Processor

A simple receipt processor

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReceiptsProcessPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptsProcessPost200Response{}

// ReceiptsProcessPost200Response struct for ReceiptsProcessPost200Response
type ReceiptsProcessPost200Response struct {
	Id string `json:"id" validate:"regexp=^\\\\S+$"`
}

type _ReceiptsProcessPost200Response ReceiptsProcessPost200Response

// NewReceiptsProcessPost200Response instantiates a new ReceiptsProcessPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptsProcessPost200Response(id string) *ReceiptsProcessPost200Response {
	this := ReceiptsProcessPost200Response{}
	this.Id = id
	return &this
}

// NewReceiptsProcessPost200ResponseWithDefaults instantiates a new ReceiptsProcessPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptsProcessPost200ResponseWithDefaults() *ReceiptsProcessPost200Response {
	this := ReceiptsProcessPost200Response{}
	return &this
}

// GetId returns the Id field value
func (o *ReceiptsProcessPost200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReceiptsProcessPost200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReceiptsProcessPost200Response) SetId(v string) {
	o.Id = v
}

func (o ReceiptsProcessPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptsProcessPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ReceiptsProcessPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptsProcessPost200Response := _ReceiptsProcessPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceiptsProcessPost200Response)

	if err != nil {
		return err
	}

	*o = ReceiptsProcessPost200Response(varReceiptsProcessPost200Response)

	return err
}

type NullableReceiptsProcessPost200Response struct {
	value *ReceiptsProcessPost200Response
	isSet bool
}

func (v NullableReceiptsProcessPost200Response) Get() *ReceiptsProcessPost200Response {
	return v.value
}

func (v *NullableReceiptsProcessPost200Response) Set(val *ReceiptsProcessPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptsProcessPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptsProcessPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptsProcessPost200Response(val *ReceiptsProcessPost200Response) *NullableReceiptsProcessPost200Response {
	return &NullableReceiptsProcessPost200Response{value: val, isSet: true}
}

func (v NullableReceiptsProcessPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptsProcessPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


